### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by miili**
Hi guys,

The document's structure is up for discussion.
I think there are more sections that we can add.

This list can also contain references to outstanding talks and introductions into DAS.

I added some initial DAS resources and enabled GitHub actions to ensure that links are alive and the Markdown follows a standard.

The `main` branch is protected, all edits to the document must undergo a review in a PR.

Best wishes,

Marius

### CODE REVIEW

**Comment by martijnende** [comment]
What is [awesome](https://github.com/sindresorhus/awesome#readme) exactly?

**Comment by miili** [comment]
This is inspired by https://github.com/vinta/awesome-python
The SAR community e.g. has https://github.com/RadarCODE/awesome-sar

> A curated list of awesome DAS resources

We can add a reference like

> Inspired by awesome-python.

**Comment by martijnende** [comment]
Another thing we could add is a list of public DAS data repositories. Some are listed [here](https://github.com/DAS-RCN/awesome-das/files/7076786/Publicly.Available.DAS.Data.Overview.pdf), maybe you know of some others.

**Comment by miili** [comment]
That looks good. Can you add this to the draft?

**Comment by miili** [comment]
Great, thanks for adding the repositories.
I will merge this as a starter :)

**Pull request merged**
